### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [rjamesvitek/_extreme_cheddar#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by rjamesvitek** [comment]
Thanks, Ken.  I've implemented
<meta name="viewport" content="width=device-width, initial-scale=1">
into the head of my application.html.erb and see that it does render differently on my phone!

**Comment by rjamesvitek** [comment]
Thanks, Ken. I've implemented
meta name="viewport" content="width=device-width, initial-scale=1"
into the head of my application.html.erb and see that it does render differently on my phone!

**Comment by kenmazaika** [comment]
![thumbs up](http://fantasy-faction.com/wp-content/uploads/2013/01/captain-picard-full-of-win.jpg)

:+1:
